################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_INTCTLR_BASE := $(UK_DRIV_BASE)/ukintctlr

$(eval $(call _import_lib,$(UK_DRIV_INTCTLR_BASE)/xpic))
$(eval $(call _import_lib,$(UK_DRIV_INTCTLR_BASE)/gic))
