UK_PLAT_BASE        := $(CONFIG_UK_BASE)/plat
UK_PLAT_COMMON_BASE := $(UK_PLAT_BASE)/common
UK_PLAT_DRIVERS_BASE:= $(UK_PLAT_BASE)/drivers

$(eval $(call import_lib,$(UK_PLAT_BASE)/xen))
$(eval $(call import_lib,$(UK_PLAT_BASE)/kvm))
$(eval $(call import_lib,$(UK_PLAT_BASE)/linuxu))
