$(eval $(call addlib_s,libukconsole_pl011,$(CONFIG_LIBUKCONSOLE_PL011)))
$(eval $(call addlib_paramprefix,libukconsole_pl011,pl011))

# TODO Remove as soon as plat dependencies go away
LIBUKCONSOLE_PL011_CINCLUDES-y  += -I$(UK_PLAT_COMMON_BASE)/include

LIBUKCONSOLE_PL011_SRCS-y += $(LIBUKCONSOLE_PL011_BASE)/pl011.c|isr
