$(eval $(call addlib_s,libuktty_pl011,$(CONFIG_LIBUKTTY_PL011)))
$(eval $(call addlib_paramprefix,libuktty_pl011,pl011))

CINCLUDES-$(CONFIG_LIBUKTTY_PL011)   += -I$(LIBUKTTY_PL011_BASE)/include
CXXINCLUDES-$(CONFIG_LIBUKTTY_PL011) += -I$(LIBUKTTY_PL011_BASE)/include

# TODO Remove as soon as plat dependencies go away
LIBUKTTY_PL011_CINCLUDES-y  += -I$(UK_PLAT_COMMON_BASE)/include

LIBUKTTY_PL011_SRCS-y += $(LIBUKTTY_PL011_BASE)/pl011.c
