$(eval $(call addlib_s,libposix_tty,$(CONFIG_LIBPOSIX_TTY)))

# Register to uklibparam, sets "posix_tty" as parameter prefix (posix_tty.*)
$(eval $(call addlib_paramprefix,libposix_tty,posix_tty))

CINCLUDES-$(CONFIG_LIBPOSIX_TTY) += -I$(LIBPOSIX_TTY_BASE)/include
CXXINCLUDES-$(CONFIG_LIBPOSIX_TTY) += -I$(LIBPOSIX_TTY_BASE)/include

LIBPOSIX_TTY_SRCS-$(CONFIG_LIBPOSIX_TTY_STDIO) += $(LIBPOSIX_TTY_BASE)/tty.c
LIBPOSIX_TTY_SRCS-$(CONFIG_LIBPOSIX_TTY_SERIAL) += $(LIBPOSIX_TTY_BASE)/serial.c
