/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

#include <uk/asm.h>

#ifndef __UK_ARCH_RISCV64_H__
#define __UK_ARCH_RISCV64_H__

#ifdef __cplusplus
extern "C" {
#endif

/* SATP */
#define UK_ARCH_RISCV64_SATP_MODE_MASK		_AC(0xF000000000000000, UL)
#define UK_ARCH_RISCV64_SATP_ASID_MASK		_AC(0x0FFFF00000000000, UL)
#define UK_ARCH_RISCV64_SATP_PPN_MASK		_AC(0x00000FFFFFFFFFFF, UL)
#define UK_ARCH_RISCV64_SATP_MODE_OFF		_AC(0, UL)
#define UK_ARCH_RISCV64_SATP_MODE_SV39		_AC(8, UL)

#define UK_ARCH_RISCV64_SATP_MODE_SHIFT		60
#define UK_ARCH_RISCV64_SATP_ASID_SHIFT		44

/* SSTATUS fields */
#define UK_ARCH_RISCV64_SSTATUS_SIE		_AC(0x00000002, UL)
#define UK_ARCH_RISCV64_SSTATUS_SPIE_SHIFT	5
#define UK_ARCH_RISCV64_SSTATUS_SPIE		\
	(_AC(1, UL) << UK_ARCH_RISCV64_SSTATUS_SPIE_SHIFT)
#define UK_ARCH_RISCV64_SSTATUS_SPP_SHIFT	8
#define UK_ARCH_RISCV64_SSTATUS_SPP		\
	(_AC(1, UL) << UK_ARCH_RISCV64_SSTATUS_SPP_SHIFT)
#define UK_ARCH_RISCV64_SSTATUS_XS		_AC(0x00018000, UL)
#define UK_ARCH_RISCV64_SSTATUS_VS		_AC(0x01800000, UL)
#define UK_ARCH_RISCV64_SSTATUS_SUM		_AC(0x00040000, UL)
#define UK_ARCH_RISCV64_SSTATUS_MXR		_AC(0x00080000, UL)
#define UK_ARCH_RISCV64_SSTATUS32_SD		_AC(0x80000000, UL)
#define UK_ARCH_RISCV64_SSTATUS64_UXL		_AC(0x0000000300000000, ULL)
#define UK_ARCH_RISCV64_SSTATUS64_SD		_AC(0x8000000000000000, ULL)

/* Supervisor trap setup */
#define UK_ARCH_RISCV64_CSR_SSTATUS		0x100
#define UK_ARCH_RISCV64_CSR_SEDELEG		0x102
#define UK_ARCH_RISCV64_CSR_SIDELEG		0x103
#define UK_ARCH_RISCV64_CSR_SIE			0x104
#define UK_ARCH_RISCV64_CSR_STVEC		0x105
#define UK_ARCH_RISCV64_CSR_SCOUNTEREN		0x106

/* Supervisor trap handling */
#define UK_ARCH_RISCV64_CSR_SSCRATCH		0x140
#define UK_ARCH_RISCV64_CSR_SEPC		0x141
#define UK_ARCH_RISCV64_CSR_SCAUSE		0x142
#define UK_ARCH_RISCV64_CSR_STVAL		0x143
#define UK_ARCH_RISCV64_CSR_SIP			0x144

/* Supervisor protection and translation */
#define UK_ARCH_RISCV64_CSR_SATP		0x180

/* Time counter */
#define UK_ARCH_RISCV64_CSR_TIME		0xc01

/* Trap handling modes */
#define UK_ARCH_RISCV64_STVEC_MODE_DIRECT	0x0
#define UK_ARCH_RISCV64_STVEC_MODE_VECTORED	0x1

/* Supervisor IRQs */
#define UK_ARCH_RISCV64_IRQ_S_SOFT		1
#define UK_ARCH_RISCV64_IRQ_S_TIMER		5
#define UK_ARCH_RISCV64_IRQ_S_EXT		9

#define UK_ARCH_RISCV64_SIP_SSIP		\
	(_AC(1, UL) << UK_ARCH_RISCV64_IRQ_S_SOFT)
#define UK_ARCH_RISCV64_SIP_STIP		\
	(_AC(1, UL) << UK_ARCH_RISCV64_IRQ_S_TIMER)
#define UK_ARCH_RISCV64_SIP_SEIP		\
	(_AC(1, UL) << UK_ARCH_RISCV64_IRQ_S_EXT)

/* Trap and exception causes */
#define UK_ARCH_RISCV64_CAUSE_MISALIGNED_FETCH		0x0
#define UK_ARCH_RISCV64_CAUSE_FETCH_ACCESS		0x1
#define UK_ARCH_RISCV64_CAUSE_ILLEGAL_INSTRUCTION	0x2
#define UK_ARCH_RISCV64_CAUSE_BREAKPOINT		0x3
#define UK_ARCH_RISCV64_CAUSE_MISALIGNED_LOAD		0x4
#define UK_ARCH_RISCV64_CAUSE_LOAD_ACCESS		0x5
#define UK_ARCH_RISCV64_CAUSE_MISALIGNED_STORE		0x6
#define UK_ARCH_RISCV64_CAUSE_STORE_ACCESS		0x7
#define UK_ARCH_RISCV64_CAUSE_USER_ECALL		0x8
#define UK_ARCH_RISCV64_CAUSE_SUPERVISOR_ECALL		0x9
#define UK_ARCH_RISCV64_CAUSE_VIRTUAL_SUPERVISOR_ECALL	0xa
#define UK_ARCH_RISCV64_CAUSE_MACHINE_ECALL		0xb
#define UK_ARCH_RISCV64_CAUSE_FETCH_PAGE_FAULT		0xc
#define UK_ARCH_RISCV64_CAUSE_LOAD_PAGE_FAULT		0xd
#define UK_ARCH_RISCV64_CAUSE_STORE_PAGE_FAULT		0xf
#define UK_ARCH_RISCV64_CAUSE_FETCH_GUEST_PAGE_FAULT	0x14
#define UK_ARCH_RISCV64_CAUSE_LOAD_GUEST_PAGE_FAULT	0x15
#define UK_ARCH_RISCV64_CAUSE_VIRTUAL_INST_FAULT	0x16
#define UK_ARCH_RISCV64_CAUSE_STORE_GUEST_PAGE_FAULT	0x17

#define UK_ARCH_RISCV64_CAUSE_INTERRUPT		\
	(_AC(1, UL) << (__riscv_xlen - 1))
#define UK_ARCH_RISCV64_CAUSE_SUPERVISOR_SOFT		\
	(UK_ARCH_RISCV64_CAUSE_INTERRUPT | UK_ARCH_RISCV64_IRQ_S_SOFT)
#define UK_ARCH_RISCV64_CAUSE_SUPERVISOR_TIMER		\
	(UK_ARCH_RISCV64_CAUSE_INTERRUPT | UK_ARCH_RISCV64_IRQ_S_TIMER)
#define UK_ARCH_RISCV64_CAUSE_SUPERVISOR_EXT		\
	(UK_ARCH_RISCV64_CAUSE_INTERRUPT | UK_ARCH_RISCV64_IRQ_S_EXT)

#ifdef __cplusplus
}
#endif

#endif /* __UK_ARCH_RISCV64_H__ */
