/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2025, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

#ifndef __UK_LCPU_REGS_H__
#error "Do not include this header directly"
#endif

#define UK_LCPU_ARM64_REGS_OFFSETOF_X0					\
	UK_PAL_ARM64_REGS_OFFSETOF_X0
#define UK_LCPU_ARM64_REGS_OFFSETOF_X1					\
	UK_PAL_ARM64_REGS_OFFSETOF_X1
#define UK_LCPU_ARM64_REGS_OFFSETOF_X2					\
	UK_PAL_ARM64_REGS_OFFSETOF_X2
#define UK_LCPU_ARM64_REGS_OFFSETOF_X3					\
	UK_PAL_ARM64_REGS_OFFSETOF_X3
#define UK_LCPU_ARM64_REGS_OFFSETOF_X4					\
	UK_PAL_ARM64_REGS_OFFSETOF_X4
#define UK_LCPU_ARM64_REGS_OFFSETOF_X5					\
	UK_PAL_ARM64_REGS_OFFSETOF_X5
#define UK_LCPU_ARM64_REGS_OFFSETOF_X6					\
	UK_PAL_ARM64_REGS_OFFSETOF_X6
#define UK_LCPU_ARM64_REGS_OFFSETOF_X7					\
	UK_PAL_ARM64_REGS_OFFSETOF_X7
#define UK_LCPU_ARM64_REGS_OFFSETOF_X8					\
	UK_PAL_ARM64_REGS_OFFSETOF_X8
#define UK_LCPU_ARM64_REGS_OFFSETOF_X9					\
	UK_PAL_ARM64_REGS_OFFSETOF_X9
#define UK_LCPU_ARM64_REGS_OFFSETOF_X10					\
	UK_PAL_ARM64_REGS_OFFSETOF_X10
#define UK_LCPU_ARM64_REGS_OFFSETOF_X11					\
	UK_PAL_ARM64_REGS_OFFSETOF_X11
#define UK_LCPU_ARM64_REGS_OFFSETOF_X12					\
	UK_PAL_ARM64_REGS_OFFSETOF_X12
#define UK_LCPU_ARM64_REGS_OFFSETOF_X13					\
	UK_PAL_ARM64_REGS_OFFSETOF_X13
#define UK_LCPU_ARM64_REGS_OFFSETOF_X14					\
	UK_PAL_ARM64_REGS_OFFSETOF_X14
#define UK_LCPU_ARM64_REGS_OFFSETOF_X15					\
	UK_PAL_ARM64_REGS_OFFSETOF_X15
#define UK_LCPU_ARM64_REGS_OFFSETOF_X16					\
	UK_PAL_ARM64_REGS_OFFSETOF_X16
#define UK_LCPU_ARM64_REGS_OFFSETOF_X17					\
	UK_PAL_ARM64_REGS_OFFSETOF_X17
#define UK_LCPU_ARM64_REGS_OFFSETOF_X18					\
	UK_PAL_ARM64_REGS_OFFSETOF_X18
#define UK_LCPU_ARM64_REGS_OFFSETOF_X19					\
	UK_PAL_ARM64_REGS_OFFSETOF_X19
#define UK_LCPU_ARM64_REGS_OFFSETOF_X20					\
	UK_PAL_ARM64_REGS_OFFSETOF_X20
#define UK_LCPU_ARM64_REGS_OFFSETOF_X21					\
	UK_PAL_ARM64_REGS_OFFSETOF_X21
#define UK_LCPU_ARM64_REGS_OFFSETOF_X22					\
	UK_PAL_ARM64_REGS_OFFSETOF_X22
#define UK_LCPU_ARM64_REGS_OFFSETOF_X23					\
	UK_PAL_ARM64_REGS_OFFSETOF_X23
#define UK_LCPU_ARM64_REGS_OFFSETOF_X24					\
	UK_PAL_ARM64_REGS_OFFSETOF_X24
#define UK_LCPU_ARM64_REGS_OFFSETOF_X25					\
	UK_PAL_ARM64_REGS_OFFSETOF_X25
#define UK_LCPU_ARM64_REGS_OFFSETOF_X26					\
	UK_PAL_ARM64_REGS_OFFSETOF_X26
#define UK_LCPU_ARM64_REGS_OFFSETOF_X27					\
	UK_PAL_ARM64_REGS_OFFSETOF_X27
#define UK_LCPU_ARM64_REGS_OFFSETOF_X28					\
	UK_PAL_ARM64_REGS_OFFSETOF_X28
#define UK_LCPU_ARM64_REGS_OFFSETOF_X29					\
	UK_PAL_ARM64_REGS_OFFSETOF_X29
#define UK_LCPU_ARM64_REGS_OFFSETOF_LR					\
	UK_PAL_ARM64_REGS_OFFSETOF_LR
#define UK_LCPU_ARM64_REGS_OFFSETOF_ELR_EL1				\
	UK_PAL_ARM64_REGS_OFFSETOF_ELR_EL1
#define UK_LCPU_ARM64_REGS_OFFSETOF_SPSR_EL1				\
	UK_PAL_ARM64_REGS_OFFSETOF_SPSR_EL1
#define UK_LCPU_ARM64_REGS_OFFSETOF_ESR_EL1				\
	UK_PAL_ARM64_REGS_OFFSETOF_ESR_EL1

#define UK_LCPU_ARM64_REGS_OFFSETOF_SP					\
	UK_PAL_REGS_OFFSETOF_SP
#define UK_LCPU_ARM64_REGS_OFFSETOF_PC					\
	UK_PAL_REGS_OFFSETOF_PC

#if !__ASSEMBLY__
#ifdef __cplusplus
extern "C" {
#endif

#define uk_lcpu_regs_get(_regs, _offset)				\
	(uk_pal_regs_get((struct uk_pal_regs *)(_regs),			\
			 UK_LCPU_ARM64_REGS_OFFSETOF_##_offset))

#define uk_lcpu_regs_set(_regs, _offset, _val)				\
	(uk_pal_regs_set((struct uk_pal_regs *)(_regs),			\
			  UK_LCPU_ARM64_REGS_OFFSETOF_##_offset, (_val)))

#ifdef __cplusplus
}
#endif
#endif /* !__ASSEMBLY__ */
