labels:
  - name: area/arch
    description: Unikraft Architecture
    color: "#7ec2f7"
    apply_on_pr_match_paths:
      - arch/**

  - name: area/docs
    description: Documentation
    color: "#db4eb8"
    apply_on_pr_match_paths:
      - doc/**
      - README.md

  - name: area/exportsyms
    description: Issue or PR relates to exporting symbols from a library
    color: "#f9822c"
    apply_on_pr_match_paths:
      - exportsyms.uk

  - name: area/include
    description: Part of include/uk
    color: "#e99695"
    apply_on_pr_match_paths:
      - include/**

  - name: area/kconfig
    description: Part of the Unikraft KConfig option system
    color: "#ed8ebd"
    apply_on_pr_match_paths:
      - Config.uk

  - name: area/lib
    description: Internal Unikraft Microlibrary
    color: "#efbf67"
    match_repos:
      - unikraft
    apply_on_pr_match_paths:
      - lib/**

  - name: area/makefile
    description: Part of the Unikraft Makefile build system
    color: "#ffe5c9"
    apply_on_pr_match_paths:
      - Makefile.uk
      - Makefile

  - name: area/plat
    description: Unikraft Patform
    color: "#f2daa9"
    apply_on_pr_match_paths:
      - plat/**

  - name: area/support
    description: Support scripts, tools, services.
    color: "#bfd4f2"
    apply_on_pr_match_paths:
      - support/**

  - name: area/workflows
    description: Issue or PR relates to GitHub action workflows
    color: "#fef2c0"
    apply_on_pr_match_paths:
      - .github/workflows/**
