labels:
  - name: kind/bug
    description: Something isn't working
    color: "#d73a4a"
  - name: kind/build-warning
    description: Issue or PR is related with a build warning
    color: "#d93f0b"

  - name: kind/enhancement
    description: New feature or request
    color: "#a2eeef"

  - name: kind/hackathon
    description: Hackathon challenge
    color: "#d4c5f9"
  
  - name: kind/maintenance
    description: Chores and meta-tasks
    color: "#a295d6"

  - name: kind/project
    description: Issue is a substantial contribution
    color: "#008672"

  - name: kind/proposal
    description: Issue discusses potential new feature or change
    color: "#dd75c0"

  - name: kind/question
    description: Issue asks a question
    color: "#e99695"

  - name: kind/quick-fix
    description: Issue is a quick fix
    color: "#1daf6b"

