labels:
  - name: new/library
    description: This PR or Issue intends to add a new library to Unikraft
    color: "#7bdb48"

  - name: new/metric
    description: New metric
    color: "#7bdb48"

  - name: new/posix-function
    description: This PR or issue intends to add a new POSIX function to Unikraft
    color: "#7bdb48"

  - name: new/primitive
    description: New internal primitive
    color: "#7bdb48"

  - name: new/syscall
    description: New syscall or registration
    color: "#7bdb48"

  - name: new/test
    description: New test
    color: "#7bdb48"

