labels:
  - name: plat/common
    description: Common to all platforms
    color: "#1d76db"
    apply_on_pr_match_paths:
      - plat/common/**
      - include/uk/plat/common/**

  - name: plat/driver
    description: Issues and PRs related to platform drivers
    color: "#750210"
    apply_on_pr_match_paths:
      - plat/drivers/**

  - name: plat/driver/gic
    description:
    color: "#ededed"
    apply_on_pr_match_paths:
      - plat/drivers/gic/**
      - plat/drivers/include/gic/**

  - name: plat/driver/ofw
    description: Issues and PRs related to open firmware drivers
    color: "#d0a0bb"
    apply_on_pr_match_paths:
      - plat/drivers/ofw/**
      - plat/drivers/include/ofw/**

  - name: plat/driver/pci
    description: Issues and PRs related to PCI driver
    color: "#d0a0bb"
    apply_on_pr_match_paths:
      - plat/common/include/pci/**

  - name: plat/driver/tap
    description: Issues and PRs related to the tap driver
    color: "#c5def5"
    apply_on_pr_match_paths:
      - plat/drivers/tap/**
      - plat/drivers/include/tap/**
      - plat/linuxu/tap_io.c

  - name: plat/driver/virtio
    description: Issues and PRs related to virtio drivers
    color: "#c5def5"
    apply_on_pr_match_paths:
      - plat/drivers/virtio/**
      - plat/drivers/include/virtio/**

  - name: plat/firecracker
    description: ''
    color: "#bfd4f2"
  - name: plat/kvm
    description: Unikraft for KVM
    color: "#1f8aa5"
    apply_on_pr_match_paths:
      - plat/kvm/**

  - name: plat/linuxu
    description: Unikraft for Linux Userspace
    color: "#bfdadc"
    apply_on_pr_match_paths:
      - plat/linux/**

  - name: plat/vmware
    description: ''
    color: "#bfd4f2"

  - name: plat/xen
    description: Unikraft for Xen
    color: "#4da81f"
    apply_on_pr_match_paths:
      - plat/xen/**
