labels:
  - name: state/accepted
    description: Accepted PR or Issue
    color: "#BBFD97"

  - name: state/action-required
    description: Action required
    color: "#006B75"

  - name: state/changes-requested
    description: Changes requested
    color: "#FA7505"

  - name: state/deferred
    description: Deferred
    color: "#763f27"

  - name: state/not-applicable
    description: Not Applicable
    color: "#52544a"

  - name: state/rejected
    description: 'Sadly this PR or Issue cannot be accepted ):'
    color: "#e93303"

  - name: state/superceded
    description: PR or Issue is no longer applicable
    color: "#5024e8"

