labels:
  - name: topic/booting
    description: Topics pertaining to the boot process
    color: "#c5def5"

  - name: topic/build
    description: Topics to do with the build system
    color: "#c5def5"

  - name: topic/ci
    description: Topics on Continious Integration/Continious Delivery
    color: "#c5def5"

  - name: topic/concurrency
    description: Topics to do with concurrency, locking
    color: "#c5def5"

  - name: topic/discussion
    description: Discussion topics
    color: "#c5def5"

  - name: topic/irq
    description: Topics on IRQ
    color: "#c5def5"

  - name: topic/metrics
    description: Topics to do with system monitoring
    color: "#c5def5"

  - name: topic/mm
    description: Topics pertaining to memory management
    color: "#c5def5"

  - name: topic/mpk
    description: Topics on Memory Protection Keys
    color: "#c5def5"

  - name: topic/muslpreview
    description: Issue or PR is related to the transition from newlib to musl
    color: "#c5def5"

  - name: topic/net
    description: Topic pertaining to networking
    color: "#c5def5"

  - name: topic/posix
    description: Topics pertaining to POSIX standard
    color: "#c5def5"

  - name: topic/primitive
    description: Topics on Unikraft primitives and essentials
    color: "#c5def5"

  - name: topic/scheduling
    description: Topics pertaining to task scheduling
    color: "#c5def5"

  - name: topic/smp
    description: PR or issues related to SMP support.
    color: "#c5def5"

  - name: topic/syscall
    description: Related to syscalls
    color: "#c5def5"

  - name: topic/testing
    description: Topics on testing
    color: "#c5def5"

  - name: topic/threading
    description: OS threading
    color: "#c5def5"

  - name: topic/tls
    description: Topics to do with Thread Level Speculation (TLS)
    color: "#c5def5"

