$(eval $(call addlib_s,libhostfs,$(CONFIG_LIBHOSTFS)))

LIBHOSTFS_CINCLUDES-y += -I$(CONFIG_UK_BASE)/plat/hyperlight/include

LIBHOSTFS_SRCS-y += $(LIBHOSTFS_BASE)/hostfs_vnops.c
LIBHOSTFS_SRCS-y += $(LIBHOSTFS_BASE)/hostfs_vfsops.c
LIBHOSTFS_SRCS-y += $(LIBHOSTFS_BASE)/hostfs_resume.c
