$(eval $(call addlib_s,librustcore,$(CONFIG_LIBRUSTCORE)))

LIBRUSTCORE_SRCS-y += $(LIBRUSTCORE_BASE)/extra.ld
LIBRUSTCORE_SRCS-$(CONFIG_LIBRUSTCORE) += $(LIBRUSTCORE_BASE)/Cargo.toml
LIBRUSTCORE_SRCS-y += $(LIBRUSTCORE_BASE)/dummy.rs

LIBRUSTCORE_CargoFLAGS-y += -Zbuild-std=core,panic_abort,alloc
LIBRUSTCORE_RUSTCFLAGS-y += -Clink-dead-code=y -Clink-self-contained=y -Clto=n -Crelocation-model=pic -Csave-temps=y 
