$(eval $(call addlib_s,libvirtio_ring,$(CONFIG_LIBVIRTIO_RING)))

# common virtio headers
LIBVIRTIO_RING_CINCLUDES-y  += -I$(UK_DRIV_LIBVIRTIO_BASE)/include
LIBVIRTIO_RING_CINCLUDES-y  += -I$(LIBVIRTIO_RING_BASE)/include

LIBVIRTIO_RING_SRCS-y += $(LIBVIRTIO_RING_BASE)/virtio_ring.c
