$(eval $(call addlib_s,ukunistd,$(CONFIG_UKUNISTD)))

CINCLUDES-y   += -I$(UKUNISTD_BASE)/include
CXXINCLUDES-y += -I$(UKUNISTD_BASE)/include
UKUNISTD_SRCS-$(CONFIG_UKUNISTD) += $(UKUNISTD_BASE)/user.c
