/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2025, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

/* Built-in fstab that is always run first; internal use only in fstab.h */

#ifndef __UK_POSIX_VFS_FSTAB_BUILTIN_H__
#define __UK_POSIX_VFS_FSTAB_BUILTIN_H__

#ifndef __UK_POSIX_VFS_FSTAB_H__
#error "Do not include this header directly"
#endif /* __UK_POSIX_VFS_FSTAB_H__ */

#if CONFIG_LIBPOSIX_VFS_FSTAB_BUILTIN
static const struct vfs_fstab_entry fstab_builtin[] = {
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI0
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_BI0_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI0_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI0_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_BI0_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI0_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_BI0_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI0 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_BI1
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_BI1_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI1_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI1_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_BI1_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI1_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_BI1_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI1 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_BI2
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_BI2_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI2_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI2_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_BI2_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI2_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_BI2_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI2 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_BI3
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_BI3_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_BI3_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI3_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_BI3_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_BI3_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_BI3_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BI3 */
};
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_BUILTIN */

#endif /* __UK_POSIX_VFS_FSTAB_BUILTIN_H__ */
