/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2025, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

/* Built-in fallback fstab; internal use only in fdtab-user.h */

#ifndef __UK_POSIX_VFS_FSTAB_FALLBACK_H__
#define __UK_POSIX_VFS_FSTAB_FALLBACK_H__

#ifndef __UK_POSIX_VFS_FSTAB_USER_H__
#error "Do not include this header directly"
#endif /* __UK_POSIX_VFS_FSTAB_USER_H__ */

#if CONFIG_LIBPOSIX_VFS_FSTAB_FALLBACK
static const struct vfs_fstab_entry fstab_fallback[] = {
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB0
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_FB0_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB0_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB0_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_FB0_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB0_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_FB0_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB0 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_FB1
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_FB1_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB1_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB1_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_FB1_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB1_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_FB1_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB1 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_FB2
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_FB2_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB2_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB2_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_FB2_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB2_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_FB2_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB2 */

#if CONFIG_LIBPOSIX_VFS_FSTAB_FB3
	{
#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DEV_ARG
	.dev = CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DEV_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DEV_ARG */
	.dev = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DEV_ARG */

	.path = CONFIG_LIBPOSIX_VFS_FSTAB_FB3_MP_ARG,

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DRIVER_ARG
	.fstype = CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DRIVER_ARG,
#else /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DRIVER_ARG */
	.fstype = "",
#endif /* !CONFIG_LIBPOSIX_VFS_FSTAB_FB3_DRIVER_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB3_FLAGS_ARG
	.flags = CONFIG_LIBPOSIX_VFS_FSTAB_FB3_FLAGS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3_FLAGS_ARG */

#ifdef CONFIG_LIBPOSIX_VFS_FSTAB_FB3_OPTS_ARG
	.opts = CONFIG_LIBPOSIX_VFS_FSTAB_FB3_OPTS_ARG,
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3_OPTS_ARG */

	.ukopts = 0x0
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_MKMP_ARG
		  | FSTAB_UKOPT_MKMP
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_MKMP_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_IFINITRD0_ARG
		  | FSTAB_UKOPT_IFINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_IFINITRD0_ARG */
#if CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_IFNOINITRD0_ARG
		  | FSTAB_UKOPT_IFNOINITRD0
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3_UKOPTS_IFNOINITRD0_ARG */
	},
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FB3 */
};
#endif /* CONFIG_LIBPOSIX_VFS_FSTAB_FALLBACK */

#endif /* __UK_POSIX_VFS_FSTAB_FALLBACK_H__ */
