$(eval $(call addlib_s,libns16550,$(CONFIG_LIBNS16550)))
$(eval $(call addlib_paramprefix,libns16550,ns16550))

# TODO: Remove as soon as plat dependencies go away
LIBNS16550_CINCLUDES-y += -I$(UK_PLAT_COMMON_BASE)/include

# FIXME: Remove as soon as bootinfo is moved out of plat/
LIBNS16550_CINCLUDES-y += -I$(UK_PLAT_COMMON_BASE)/include

LIBNS16550_SRCS-$(CONFIG_ARCH_ARM_64) += $(LIBNS16550_BASE)/ns16550.c|isr
LIBNS16550_SRCS-$(CONFIG_ARCH_X86_64) += $(LIBNS16550_BASE)/com.c|isr
