/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2021, Karlsruhe Institute of Technology. All rights reserved.
 * Copyright (c) 2025, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

#ifndef __PLAT_CMN_ARM_TRAPS_H__
#define __PLAT_CMN_ARM_TRAPS_H__

#include <uk/arch/traps.h>

#define DECLARE_TRAP_EVENT(event)	\
	UK_EVENT(event)

static const char *arm64_exception_table[ARM64_EXCEPTION_MAX] = {
	"invalid op",     /* ARM64_EXCEPTION_INVALID_OP */
	"debug",          /* ARM64_EXCEPTION_DEBUG */
	"page fault",     /* ARM64_EXCEPTION_PAGE_FAULT */
	"bus error",      /* ARM64_EXCEPTION_BUS_ERROR */
	"floating point", /* ARM64_EXCEPTION_MATH */
	"security",       /* ARM64_EXCEPTION_SECURITY */
	"system call",    /* ARM64_EXCEPTION_SYSCALL */
};

/* Mapping of the fault status code (FSC) for instruction and data aborts to
 * trap type (either page fault or bus error). Zero means invalid. The map
 * takes 64 bytes but saves a ton of comparisons.
 */
static const __u8 arm64_exception_map[] = {
	[ESR_ISS_ABRT_FSC_ADDR_L0]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ADDR_L1]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ADDR_L2]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ADDR_L3]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_TRANS_L0]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_TRANS_L1]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_TRANS_L2]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_TRANS_L3]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ACCF_L0]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ACCF_L1]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ACCF_L2]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_ACCF_L3]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_PERM_L0]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_PERM_L1]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_PERM_L2]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_PERM_L3]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_SYNC]			= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_TAG]			= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_SYNC_PT_LM1]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_PT_L0]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_PT_L1]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_PT_L2]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_PT_L3]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC_PT_LM1]	= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC_PT_L0]	= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC_PT_L1]	= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC_PT_L2]	= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_SYNC_ECC_PT_L3]	= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_ALIGN]		= ARM64_EXCEPTION_BUS_ERROR,
	[ESR_ISS_ABRT_FSC_ADDR_LM1]		= ARM64_EXCEPTION_PAGE_FAULT,
	[ESR_ISS_ABRT_FSC_TRANS_LM1]		= ARM64_EXCEPTION_PAGE_FAULT
};

#endif /* __PLAT_CMN_ARM_TRAPS_H__ */
