################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_SEV_BASE := $(UK_DRIV_BASE)/amd-sev

$(eval $(call import_lib,$(UK_DRIV_SEV_BASE)/uksev))
