$(eval $(call addlib_s,libukps2,$(CONFIG_LIBUKPS2)))

# FIXME: Remove this and make the library self contained
LIBUKPS2_CINCLUDES-$(CONFIG_LIBUKPS2_KBD) += -I$(UK_PLAT_COMMON_BASE)/include

LIBUKPS2_SRCS-$(CONFIG_LIBUKPS2_KBD) += $(LIBUKPS2_BASE)/kbd.c|isr
