$(eval $(call addlib_s,libukfs_virtiofs,$(CONFIG_LIBUKFS_VIRTIOFS)))

LIBUKFS_VIRTIOFS_SRCS-y += $(LIBUKFS_VIRTIOFS_BASE)/virtiofs.c
LIBUKFS_VIRTIOFS_SRCS-y += $(LIBUKFS_VIRTIOFS_BASE)/virtiofs-fuse.c
