define _uk_libparam_libprefix_set =
$(eval $(call uc,$(2))_CFLAGS += -DUK_LIBPARAM_LIBPREFIX=$(1))
$(eval $(call uc,$(2))_CXXFLAGS += -DUK_LIBPARAM_LIBPREFIX=$(1))
$(eval $(call uc,$(2))_ASFLAGS += -DUK_LIBPARAM_LIBPREFIX=$(1))
endef

# Set an alternative library prefix for library parameters
# uk_libparam_prefix_set 1:library_name, 2:new_prefix
define uk_libparam_libprefix_set =
$(if $(2),\
$(eval name := $(2)),\
$(eval name := $(1)))
$(eval $(call _uk_libparam_libprefix_set,$(name),$(1),$(call uc,$(1))))
endef

# Deprecated registration function
# WARNING: This interface is here for backwards compatibility and will be
#          removed in the near future.
define addlib_paramprefix =
$(call uk_libparam_libprefix_set,$(1),$(2))
endef
