################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_FIRMWARE_BASE := $(UK_DRIV_BASE)/firmware

$(eval $(call import_lib,$(UK_DRIV_FIRMWARE_BASE)/ukefi))
$(eval $(call import_lib,$(UK_DRIV_FIRMWARE_BASE)/ukacpi))
$(eval $(call import_lib,$(UK_DRIV_FIRMWARE_BASE)/uksmccc))
