/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2025, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

#ifndef __UK_PLAT_PAL_REGS_H__
#error "Do not include this header directly"
#endif

#define UK_PAL_X86_64_REGS_OFFSETOF_R15					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R15
#define UK_PAL_X86_64_REGS_OFFSETOF_R14					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R14
#define UK_PAL_X86_64_REGS_OFFSETOF_R13					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R13
#define UK_PAL_X86_64_REGS_OFFSETOF_R12					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R12
#define UK_PAL_X86_64_REGS_OFFSETOF_RBP					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RBP
#define UK_PAL_X86_64_REGS_OFFSETOF_RBX					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RBX
#define UK_PAL_X86_64_REGS_OFFSETOF_R11					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R11
#define UK_PAL_X86_64_REGS_OFFSETOF_R10					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R10
#define UK_PAL_X86_64_REGS_OFFSETOF_R9					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R9
#define UK_PAL_X86_64_REGS_OFFSETOF_R8					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_R8
#define UK_PAL_X86_64_REGS_OFFSETOF_RAX					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RAX
#define UK_PAL_X86_64_REGS_OFFSETOF_RCX					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RCX
#define UK_PAL_X86_64_REGS_OFFSETOF_RDX					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RDX
#define UK_PAL_X86_64_REGS_OFFSETOF_RSI					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RSI
#define UK_PAL_X86_64_REGS_OFFSETOF_RDI					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RDI
#define UK_PAL_X86_64_REGS_OFFSETOF_ORIG_RAX				\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_ORIG_RAX
#define UK_PAL_X86_64_REGS_OFFSETOF_RIP					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RIP
#define UK_PAL_X86_64_REGS_OFFSETOF_CS					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_CS
#define UK_PAL_X86_64_REGS_OFFSETOF_RFLAGS				\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RFLAGS
#define UK_PAL_X86_64_REGS_OFFSETOF_RSP					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_RSP
#define UK_PAL_X86_64_REGS_OFFSETOF_SS					\
	UK_PLAT_NATIVE_X86_64_REGS_OFFSETOF_SS
