$(eval $(call addlib_s,librustfs,$(CONFIG_LIBRUSTFS)))

LIBRUSTFS_CFLAGS-$(call gcc_version_ge,8,0) += -Wno-cast-function-type

LIBRUSTFS_SRCS-$(LIBRUSTFS) += $(LIBRUSTFS_BASE)/rustfs_vfsops.c
LIBRUSTFS_SRCS-$(LIBRUSTFS) += $(LIBRUSTFS_BASE)/rustfs_vnops.c
LIBRUSTFS_SRCS-$(LIBRUSTFS) += $(LIBRUSTFS_BASE)/Cargo.toml
