#ifndef __UK_LCPU_REGS_H__
#error "Do not include this header directly"
#endif

#define UK_LCPU_RISCV64_REGS_OFFSETOF_T0				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T0
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T1				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T1
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T2				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T2
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T3				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T3
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T4				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T4
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T5				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T5
#define UK_LCPU_RISCV64_REGS_OFFSETOF_T6				\
	UK_PAL_RISCV64_REGS_OFFSETOF_T6
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A0				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A0
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A1				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A1
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A2				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A2
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A3				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A3
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A4				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A4
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A5				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A5
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A6				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A6
#define UK_LCPU_RISCV64_REGS_OFFSETOF_A7				\
	UK_PAL_RISCV64_REGS_OFFSETOF_A7
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S0				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S0
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S1				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S1
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S2				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S2
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S3				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S3
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S4				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S4
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S5				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S5
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S6				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S6
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S7				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S7
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S8				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S8
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S9				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S9
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S10				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S10
#define UK_LCPU_RISCV64_REGS_OFFSETOF_S11				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S11
#define UK_LCPU_RISCV64_REGS_OFFSETOF_RA				\
	UK_PAL_RISCV64_REGS_OFFSETOF_RA
#define UK_LCPU_RISCV64_REGS_OFFSETOF_TP				\
	UK_PAL_RISCV64_REGS_OFFSETOF_TP

#define UK_LCPU_RISCV64_REGS_OFFSETOF_FP				\
	UK_PAL_RISCV64_REGS_OFFSETOF_S0

#define UK_LCPU_RISCV64_REGS_OFFSETOF_SP				\
	UK_PAL_REGS_OFFSETOF_SP
#define UK_LCPU_RISCV64_REGS_OFFSETOF_PC				\
	UK_PAL_REGS_OFFSETOF_PC

#if !__ASSEMBLY__
#ifdef __cplusplus
extern "C" {
#endif

#define uk_lcpu_regs_get(_regs, _offset)				\
	(uk_pal_regs_get((struct uk_pal_regs *)(_regs),			\
			 UK_LCPU_RISCV64_REGS_OFFSETOF_##_offset))

#define uk_lcpu_regs_set(_regs, _offset, _val)				\
	(uk_pal_regs_set((struct uk_pal_regs *)(_regs),			\
			 UK_LCPU_RISCV64_REGS_OFFSETOF_##_offset, (_val)))

#ifdef __cplusplus
}
#endif
#endif /* !__ASSEMBLY__ */
