################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_BASE := $(CONFIG_UK_BASE)/drivers

$(eval $(call _import_lib,$(UK_DRIV_BASE)/amd-sev))
$(eval $(call _import_lib,$(UK_DRIV_BASE)/ukbus))
$(eval $(call _import_lib,$(UK_DRIV_BASE)/ukintctlr))
