################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_BASE := $(CONFIG_UK_BASE)/drivers

$(eval $(call import_lib,$(UK_DRIV_BASE)/ukbus))
$(eval $(call import_lib,$(UK_DRIV_BASE)/ukintctlr))
$(eval $(call import_lib,$(UK_DRIV_BASE)/uktty))
$(eval $(call import_lib,$(UK_DRIV_BASE)/virtio))
$(eval $(call import_lib,$(UK_DRIV_BASE)/xen))
