################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_CCA_BASE := $(UK_DRIV_BASE)/arm-cca

$(eval $(call _import_lib,$(UK_DRIV_CCA_BASE)/ukrsi))
