/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2023, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */
#include <uk/libparam.h>
#include <uk/essentials.h>
#include "environ.h"

/*
 * Size the array
 */
static char *__init_env[1 /* null termination */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP0_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP0_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP1_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP1_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP2_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP2_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP3_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP3_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP4_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP4_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP5_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP5_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP6_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP6_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP7_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP7_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP8_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP8_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP9_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP9_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP10_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP10_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP11_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP11_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP12_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP12_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP13_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP13_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP14_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP14_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP15_NOTEMPTY
	+ 1
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP15_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_LIBPARAM
	+ CONFIG_LIBPOSIX_ENVIRON_LIBPARAM_MAXCOUNT
#endif /* CONFIG_LIBPOSIX_ENVIRON_LIBPARAM */
	] = {
#if CONFIG_LIBPOSIX_ENVIRON_ENVP0_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP0,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP0_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP1_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP1,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP1_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP2_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP2,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP2_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP3_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP3,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP3_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP4_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP4,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP4_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP5_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP5,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP5_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP6_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP6,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP6_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP7_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP7,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP7_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP8_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP8,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP8_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP9_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP9,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP9_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP10_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP10,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP10_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP11_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP11,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP11_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP12_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP12,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP12_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP13_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP13,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP13_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP14_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP14,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP14_NOTEMPTY */
#if CONFIG_LIBPOSIX_ENVIRON_ENVP15_NOTEMPTY
	CONFIG_LIBPOSIX_ENVIRON_ENVP15,
#endif /* CONFIG_LIBPOSIX_ENVIRON_ENVP15_NOTEMPTY */
	NULL /* termination */
};

#if CONFIG_LIBPOSIX_ENVIRON_LIBPARAM
UK_LIBPARAM_PARAM_ARR_ALIAS(vars,
			    &(__init_env[ARRAY_SIZE(__init_env) -
				CONFIG_LIBPOSIX_ENVIRON_LIBPARAM_MAXCOUNT - 1]),
			    charp,
			    CONFIG_LIBPOSIX_ENVIRON_LIBPARAM_MAXCOUNT,
			    "Environment variables");
#endif

char **__environ = __init_env;
__weak_alias(__environ, ___environ);
__weak_alias(__environ, _environ);
__weak_alias(__environ, environ);
