/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */

#ifndef __UK_PLAT_XEN_PAGE_H__
#define __UK_PLAT_XEN_PAGE_H__

/* Xen shares fundamental page definitions with native platform */
#include <uk/plat/native/page.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Constants for each paging level */
#define UK_PLAT_XEN_PAGE_SHIFT_Lx	UK_PLAT_NATIVE_PAGE_SHIFT_Lx
#define UK_PLAT_XEN_PAGE_Lx_SHIFT	UK_PLAT_NATIVE_PAGE_Lx_SHIFT
#define UK_PLAT_XEN_PAGE_Lx_SIZE	UK_PLAT_NATIVE_PAGE_Lx_SIZE
#define UK_PLAT_XEN_PAGE_Lx_MASK	UK_PLAT_NATIVE_PAGE_Lx_MASK
#define UK_PLAT_XEN_PAGE_Lx_ALIGN_UP	UK_PLAT_NATIVE_PAGE_Lx_ALIGN_UP
#define UK_PLAT_XEN_PAGE_Lx_ALIGN_DOWN	UK_PLAT_NATIVE_PAGE_Lx_ALIGN_DOWN
#define UK_PLAT_XEN_PAGE_Lx_ALIGNED	UK_PLAT_NATIVE_PAGE_Lx_ALIGNED

/* Convenience macros for regular, large, and huge pages */
#define UK_PLAT_XEN_PAGE_LEVEL		UK_PLAT_NATIVE_PAGE_LEVEL
#define UK_PLAT_XEN_PAGE_SHIFT		UK_PLAT_NATIVE_PAGE_SHIFT
#define UK_PLAT_XEN_PAGE_SIZE		UK_PLAT_NATIVE_PAGE_SIZE
#define UK_PLAT_XEN_PAGE_MASK		UK_PLAT_NATIVE_PAGE_MASK
#define UK_PLAT_XEN_PAGE_LARGE_LEVEL	UK_PLAT_NATIVE_PAGE_LARGE_LEVEL
#define UK_PLAT_XEN_PAGE_LARGE_SHIFT	UK_PLAT_NATIVE_PAGE_LARGE_SHIFT
#define UK_PLAT_XEN_PAGE_LARGE_SIZE	UK_PLAT_NATIVE_PAGE_LARGE_SIZE
#define UK_PLAT_XEN_PAGE_LARGE_MASK	UK_PLAT_NATIVE_PAGE_LARGE_MASK
#define UK_PLAT_XEN_PAGE_HUGE_LEVEL	UK_PLAT_NATIVE_PAGE_HUGE_LEVEL
#define UK_PLAT_XEN_PAGE_HUGE_SHIFT	UK_PLAT_NATIVE_PAGE_HUGE_SHIFT
#define UK_PLAT_XEN_PAGE_HUGE_SIZE	UK_PLAT_NATIVE_PAGE_HUGE_SIZE
#define UK_PLAT_XEN_PAGE_HUGE_MASK	UK_PLAT_NATIVE_PAGE_HUGE_MASK

/* Alignment macros */
#define UK_PLAT_XEN_PAGE_ALIGN_UP		\
	UK_PLAT_NATIVE_PAGE_ALIGN_UP

#define UK_PLAT_XEN_PAGE_ALIGN_DOWN		\
	UK_PLAT_NATIVE_PAGE_ALIGN_DOWN

#define UK_PLAT_XEN_PAGE_ALIGNED		\
	UK_PLAT_NATIVE_PAGE_ALIGNED

#define UK_PLAT_XEN_PAGE_LARGE_ALIGN_UP		\
	UK_PLAT_NATIVE_PAGE_LARGE_ALIGN_UP

#define UK_PLAT_XEN_PAGE_LARGE_ALIGN_DOWN	\
	UK_PLAT_NATIVE_PAGE_LARGE_ALIGN_DOWN

#define UK_PLAT_XEN_PAGE_LARGE_ALIGNED		\
	UK_PLAT_NATIVE_PAGE_LARGE_ALIGNED

#define UK_PLAT_XEN_PAGE_HUGE_ALIGN_UP		\
	UK_PLAT_NATIVE_PAGE_HUGE_ALIGN_UP

#define UK_PLAT_XEN_PAGE_HUGE_ALIGN_DOWN	\
	UK_PLAT_NATIVE_PAGE_HUGE_ALIGN_DOWN

#define UK_PLAT_XEN_PAGE_HUGE_ALIGNED		\
	UK_PLAT_NATIVE_PAGE_HUGE_ALIGNED

/* Page Protections */
#define UK_PLAT_XEN_PAGE_ATTR_PROT_NONE		\
	UK_PLAT_NATIVE_PAGE_ATTR_PROT_NONE

#define UK_PLAT_XEN_PAGE_ATTR_PROT_READ		\
	UK_PLAT_NATIVE_PAGE_ATTR_PROT_READ

#define UK_PLAT_XEN_PAGE_ATTR_PROT_WRITE	\
	UK_PLAT_NATIVE_PAGE_ATTR_PROT_WRITE

#define UK_PLAT_XEN_PAGE_ATTR_PROT_EXEC		\
	UK_PLAT_NATIVE_PAGE_ATTR_PROT_EXEC

#if !__ASSEMBLY__

#define UK_PLAT_XEN_PAGE_Lx_HAS		UK_PLAT_NATIVE_PAGE_Lx_HAS

#define UK_PLAT_XEN_PAGE_Lx_IS		UK_PLAT_NATIVE_PAGE_Lx_IS

#endif /* !__ASSEMBLY__ */

#ifdef __cplusplus
}
#endif

#endif /* __UK_PLAT_XEN_PAGE_H__ */
