$(eval $(call addlib_s,libvirtio_bus,$(CONFIG_LIBVIRTIO_BUS)))

LIBVIRTIO_BUS_CINCLUDES-y  += -I$(LIBVIRTIO_BUS_BASE)/include

# common virtio headers
LIBVIRTIO_BUS_CINCLUDES-y  += -I$(LIBVIRTIO_RING_BASE)/include
LIBVIRTIO_BUS_CINCLUDES-y  += -I$(UK_DRIV_LIBVIRTIO_BASE)/include

# TODO Remove as soon as plat dependencies go away
LIBVIRTIO_BUS_CINCLUDES-y  += -I$(UK_PLAT_COMMON_BASE)/include

LIBVIRTIO_BUS_SRCS-y += $(LIBVIRTIO_BUS_BASE)/virtio_bus.c
