################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_RANDOM_BASE := $(UK_DRIV_BASE)/ukrandom

$(eval $(call import_lib,$(UK_DRIV_RANDOM_BASE)/lcpu))
