define build_elf64_to_32 =
	@$(SCRIPTS_DIR)/elf64_to_32.py $(1) -o $(1)
endef

BINFO_FLAGS := -a $(CONFIG_UK_ARCH)

ifeq ($(CONFIG_UKPLAT_MEMRNAME),y)
BINFO_FLAGS += -n
endif

define build_bootinfo =
	$(call build_cmd,UKBI,,$(1).bootinfo,\
		$(SCRIPTS_DIR)/mkbootinfo.py $(1) $(1).bootinfo $(BINFO_FLAGS) && \
		$(OBJCOPY) $(1) --update-section .uk_bootinfo=$(1).bootinfo)
endef
