define build_elf64_to_32 =
	@$(SCRIPTS_DIR)/elf64_to_32.py $(1) -o $(1)
endef

BINFO_FLAGS := -a $(CONFIG_UK_ARCH)

ifeq ($(CONFIG_UKPLAT_MEMRNAME),y)
BINFO_FLAGS += -n
endif

define build_bootinfo =
	$(call build_cmd,UKBI,,$(1).bootinfo,\
		$(SCRIPTS_DIR)/mkbootinfo.py --min-address $(2) $(1) $(1).bootinfo $(BINFO_FLAGS) && \
		$(OBJCOPY) $(1) --update-section .uk_bootinfo=$(1).bootinfo)
endef

define build_efi =
	@$(SCRIPTS_DIR)/mkefi.py $(1)
endef

define get_symbol_addr =
	0x$(shell nm -B $(2) | grep ' '$(1)'$$' | cut -d' ' -f1)
endef
