$(eval $(call addlib_s,libukalloc,$(CONFIG_LIBUKALLOC)))

CINCLUDES-$(CONFIG_LIBUKALLOC)		+= -I$(LIBUKALLOC_BASE)/include
CXXINCLUDES-$(CONFIG_LIBUKALLOC)	+= -I$(LIBUKALLOC_BASE)/include

LIBUKALLOC_CFLAGS-y	+= -fno-sanitize=kernel-address

LIBUKALLOC_SRCS-y += $(LIBUKALLOC_BASE)/alloc.c
