ARCHFLAGS     += -D__RISCV_64__ -mabi=lp64d -march=rv64gc \
		 -mcmodel=medany -mno-fdiv

ISR_ARCHFLAGS += -D__RISCV_64__ -mabi=lp64d -march=rv64gc \
		 -mcmodel=medany -mno-fdiv

LDFLAGS      += -mabi=lp64d -march=rv64gc -mcmodel=medany -mno-fdiv

CINCLUDES   += -I$(CONFIG_UK_BASE)/arch/riscv/riscv64/include
ASINCLUDES  += -I$(CONFIG_UK_BASE)/arch/riscv/riscv64/include
CXXINCLUDES += -I$(CONFIG_UK_BASE)/arch/riscv/riscv64/include

CINCLUDES   += -I$(CONFIG_UK_BASE)/arch/include
ASINCLUDES  += -I$(CONFIG_UK_BASE)/arch/include
CXXINCLUDES += -I$(CONFIG_UK_BASE)/arch/include
