#ifndef __UK_PLAT_NATIVE_ARCH_PAGE_H__
#define __UK_PLAT_NATIVE_ARCH_PAGE_H__

#include <uk/asm/paging.h>

#ifdef __cplusplus
extern "C" {
#endif

#if CONFIG_LIBUKPLAT_NATIVE_PAGE

#define UK_PLAT_NATIVE_PAGE_LEVEL		PAGE_LEVEL
#define UK_PLAT_NATIVE_PAGE_SHIFT		PAGE_SHIFT
#define UK_PLAT_NATIVE_PAGE_SIZE		PAGE_SIZE
#define UK_PLAT_NATIVE_PAGE_MASK		PAGE_MASK

#define UK_PLAT_NATIVE_PAGE_LARGE_LEVEL		PAGE_LARGE_LEVEL
#define UK_PLAT_NATIVE_PAGE_LARGE_SHIFT		PAGE_LARGE_SHIFT
#define UK_PLAT_NATIVE_PAGE_LARGE_SIZE		PAGE_LARGE_SIZE
#define UK_PLAT_NATIVE_PAGE_LARGE_MASK		PAGE_LARGE_MASK

#define UK_PLAT_NATIVE_PAGE_HUGE_LEVEL		PAGE_HUGE_LEVEL
#define UK_PLAT_NATIVE_PAGE_HUGE_SHIFT		PAGE_HUGE_SHIFT
#define UK_PLAT_NATIVE_PAGE_HUGE_SIZE		PAGE_HUGE_SIZE
#define UK_PLAT_NATIVE_PAGE_HUGE_MASK		PAGE_HUGE_MASK

#define UK_PLAT_NATIVE_PAGE_Lx_SHIFT(lvl)		PAGE_Lx_SHIFT(lvl)
#define UK_PLAT_NATIVE_PAGE_SHIFT_Lx(shift)		PAGE_SHIFT_Lx(shift)

#define UK_PLAT_NATIVE_PAGE_ATTR_PROT_NONE		PAGE_ATTR_PROT_NONE
#define UK_PLAT_NATIVE_PAGE_ATTR_PROT_READ		PAGE_ATTR_PROT_READ
#define UK_PLAT_NATIVE_PAGE_ATTR_PROT_WRITE		PAGE_ATTR_PROT_WRITE
#define UK_PLAT_NATIVE_PAGE_ATTR_PROT_EXEC		PAGE_ATTR_PROT_EXEC

#if !__ASSEMBLY__

#define UK_PLAT_NATIVE_PAGE_Lx_HAS(lvl)			PAGE_Lx_HAS(lvl)
#define UK_PLAT_NATIVE_PAGE_Lx_IS(pte, lvl)		PAGE_Lx_IS(pte, lvl)

#endif /* !__ASSEMBLY__ */

#endif /* CONFIG_LIBUKPLAT_NATIVE_PAGE */

#ifdef __cplusplus
}
#endif
#endif /* __UK_PLAT_NATIVE_ARCH_PAGE_H__ */
