################################################################################
#
# Driver registrations
#
################################################################################

UK_DRIV_INPUT_BASE := $(UK_DRIV_BASE)/input

$(eval $(call import_lib,$(UK_DRIV_INPUT_BASE)/ukps2))
